[project]
name = "ghactionsdashboard"
version = "0.1.0"
description = "Streamlit dashboard for tracking CI/CD pipelines"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.9"

dependencies = [
  "streamlit>=1.32",
  "pandas>=2.2",
  "openpyxl"
]
