name: Call Main Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  docker-build:
    permissions: write-all
    uses: iiakovleva-l/ci-cd-workflows/.github/workflows/main-build.yml@main
    with:
      build-type: docker
    secrets: inherit