name: Call Docker Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  docker-build:
    permissions: write-all
    uses: iiakovleva-l/ci-cd-workflows/.github/workflows/build-docker.yml@main
    with:
      dockerfile: Dockerfile
      context: .
      image_tags: ghcr.io/${{ github.repository }}:latest
      registry: ghcr.io
      push: true
    secrets: inherit