name: Call Docker Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  docker-build:
    uses: iiakovleva-l/ci-cd-workflows/.github/workflows/build-docker.yml@main
    with:
      dockerfile: Dockerfile
      context: .
      image_tags: |
        ghcr.io/iiakovleva-l/ghactionsdashboard:latest
        ghcr.io/iiakovleva-l/ghactionsdashboard:${{ github.sha }}
      registry: ghcr.io
      push: true
    secrets: inherit